export const api_baseURL = "https://mick-dunaev-login-server.herokuapp.com/api/"
export const api_authenticate = api_baseURL + "authenticate"
export const api_register = api_baseURL + "register"
export const api_getUserProfile = api_baseURL + "getUserProfile"
export const api_checkToken = api_baseURL + "checkToken"